### ISSUE TITLE
(Small) Noticed  a typo on the Sign In Page

### ISSUE THREAD

**Issue by TomSmithson** [codemyjourney/Ecommerce-Website#1]
A very small mistake but on the sign in page, it says "eamil" instead of "email".
Hope this is helpful!
Have a nice day!

<img width="621" alt="image" src="https://user-images.githubusercontent.com/20268418/85869211-4d344b80-b7c3-11ea-8e0f-c374ec18e5fb.png">

**Comment by stacykutyepov** [comment]
Thank you so much! I will fix it!

Best regards,
Stacy

On 26 Jun 2020, at 10:40 AM, Tom Smithson <notifications@github.com> wrote:

﻿

A very small mistake but on the sign in page, it says "eamil" instead of "email".
Hope this is helpful!
Have a nice day!

[image]<https://user-images.githubusercontent.com/20268418/85869211-4d344b80-b7c3-11ea-8e0f-c374ec18e5fb.png>
